name: E2E
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
      - name: run tests
        env:
          OC_LOGIN_TOKEN: ${{ secrets.OC_LOGIN_TOKEN }}
          OC_SERVER_URL: ${{ secrets.OC_SERVER_URL }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          DEVELOPER_HUB_URL: ${{ secrets.DEVELOPER_HUB_URL }}
        run: |
          oc login --server $OC_SERVER_URL --token $OC_LOGIN_TOKEN --insecure-skip-tls-verify

          cd e2e-tests
          npm install
          npm test